version: '3.9'

services:
  wordpress:
    build: '.'
    container_name: 'wordpress'
    restart: 'always'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db' 
      WORDPRESS_DB_USER: 'wpuser'
      WORDPRESS_DB_PASSWORD: 'wppassword'
      WORDPRESS_DB_NAME: 'wpdb'
      WORDPRESS_TABLE_PREFIX: 'dev_'
      WORDPRESS_DEBUG: "1"
    volumes:
      - './wordpress:/var/www/html/'

  db:
    image: 'mysql'
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'A@#!UnbOLTCR564'
      MYSQL_DATABASE: 'wpdb'
      MYSQL_USER: 'wpuser'
      MYSQL_PASSWORD: 'wppassword'
    restart: 'always'
    volumes:
      - 'db:/var/lib/mysql'

  adminer:
    container_name: 'adminer'
    depends_on:
      - 'db'
    image: 'adminer'
    restart: 'always'
    ports:
      - '8888:8080'

networks:
  dev-network:

volumes:
  db:
